# Generated by Django 6.0.1 on 2026-01-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                ("seats", models.PositiveIntegerField()),
                ("max_rent_days", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("rented", "Rented")],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("categories", models.ManyToManyField(to="cars.carcategory")),
            ],
        ),
    ]
